ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('',include('product.urls')),
    path('my_admin/',include('my_admin.urls')),
    # path('',views.loginpage,name='login'),
    # path('home/',views.Homepage,name='home'),
    # path('logout/',views.Logoutpage,name='logout'),
    # path('signup/',views.signup_page,name='signup'),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

user/urls.py
from django.urls import path
from .views import test, register, user_login, home, user_logout

urlpatterns =[
    # path('',home,name='home'),
    path('register/',register,name = 'register'),
    path('login/',user_login,name='user_login'),
    path('logout/',user_logout,name='user_logout')
]
    

user/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    name = models.CharField(max_length=100)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import MyUser
from django import forms

class CreateUserForm(UserCreationForm):
    # Adding status field with custom style
    # status = forms.ChoiceField(
    #     widget=forms.Select(attrs={'class': 'form-control'})
    # )

   class Meta:
        model = MyUser
        fields = ['name', 'email', 'password1', 'password2']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            # Here we override the widgets for password1 and password2 to ensure the class is applied
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.views.decorators.cache import never_cache
from django.contrib.auth.models import User
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def test(request):
    form = CreateUserForm()
    context = {'form':form}
    return render(request,'user/test.html', context)

def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form_data =request.POST.copy()
        form = CreateUserForm(form_data)
        if form.is_valid() :
            form.save()
            return redirect('login')
    context = {'form':form}  
    return render(request,'user/register.html',context)    

def user_login(request):
    if request.method =='POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            print("user not found")
            return redirect('user_login')
    return render(request,'user/login.html')

def user_logout(request):
    logout(request)
    return redirect('user_login')



@never_cache
def home(request):
    if request.user.is_authenticated:
        return render(request,'product/home.html')
    return redirect('user_login')


# @never_cache
# def loginpage(request):
#     if not request.user.is_authenticated:
#         if request.method == 'POST':
#             username = request.POST['username']
#             password = request.POST['password']
            
#             user = authenticate(request, username = username, password = password)
#             if user is not None:
#                 login(request,user)
#                 # request.session['username'] = username
#                 return redirect('home')
#             else:
#                 messages.error(request,"Invalid username or password")
#                 return redirect('login')
#         return render(request,'login.html')
    
#     return redirect('home')

# def signup_page(request):
#      if request.method == 'POST':
#         username = request.POST['username']
#         first_name = request.POST['firstname']
#         password = request.POST['password']
#         password1= request.POST['password1']
#         email    = request.POST['email']

#         if password == password1:
#             if User.objects.filter(username=username).exists():
#                 messages.error(request, 'Username already exists')
#                 return redirect('signup')
#             else:
#                 user = User.objects.create_user(username, email, password)
#                 user.first_name = first_name
#                 user.save()
#                 messages.success(request, 'You have successfully signed up!')
#                 return redirect('login')
#         else:
#             messages.error(request, 'Passwords do not match')
#             return redirect('signup')
    
#      else:
#          return render(request,'signup.html')

user/templates/user/index.html
{% load static%}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Vase shop | eCommers</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- CSS here -->
    {% comment %} <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'img\css\bootstrap.min.css' %}">
</head>

<body>
    <!--? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header header-sticky" >
                <div class="container-fluid">
                    <div class="menu-wrapper" style = 'height: 70px'>
                        <!-- Logo -->
                        <div class="logo">
                            <a href="{% url 'home'%}"><img style = 'height: 75px ; width:300px' src="{% static 'assets/img/vases/vase logo.png' %}" alt=""></a>
                        </div>
                        <!-- Main-menu -->
                        <div class="main-menu d-none d-lg-block">
                            <nav>                                                
                                <ul id="navigation">  
                                    <li><a href="{% url 'home'%}">Home</a></li>
                                    <li><a href="shop.html">shop</a></li>
                                    <li><a href="about.html">about</a></li>
                                    <li ><a href="#">Latest</a>
                                        <ul class="submenu">
                                            <li><a href="shop.html"> Product list</a></li>
                                            <li><a href="product_details.html"> Product Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="blog.html">Blog</a>
                                        <ul class="submenu">
                                            <li><a href="blog.html">Blog</a></li>
                                            <li><a href="blog-details.html">Blog Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Pages</a>
                                        <ul class="submenu">
                                            <li><a href="{% url 'user_login'%}">Login</a></li>
                                            <li><a href="cart.html">Cart</a></li>
                                            <li><a href="elements.html">Element</a></li>
                                            <li><a href="confirmation.html">Confirmation</a></li>
                                            <li><a href="checkout.html">Product Checkout</a></li>
                                        </ul>
                                    </li>
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'user_logout'%}">Logout</a></li>
                                    {% else %}
                                    <li><a href="{% url 'user_login'%}">Login</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                        <!-- Header Right -->
                        <div class="header-right">
                            <ul>
                                <li>
                                    <div class="nav-search search-switch">
                                        <span class="flaticon-search"></span>
                                    </div>
                                </li>
                                <li> <a href="login.html"><span class="flaticon-user"></span></a></li>
                                <li><a href="cart.html"><span class="flaticon-shopping-cart"></span></a> </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>
   {% block body %}
   {% endblock body%}
    <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a href="index.html"><img style = 'height: 60px ; width:250px' src="{% static 'assets/img/vases/vase logo.png' %}" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>Asorem ipsum adipolor sdit amet, consectetur adipisicing elitcf sed do eiusmod tem.</p>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
                                    <li><a href="#">About</a></li>
                                    <li><a href="#"> Offers & Discounts</a></li>
                                    <li><a href="#"> Get Coupon</a></li>
                                    <li><a href="#">  Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>New Products</h4>
                                <ul>
                                    <li><a href="#">Woman Cloth</a></li>
                                    <li><a href="#">Fashion Accessories</a></li>
                                    <li><a href="#"> Man Accessories</a></li>
                                    <li><a href="#"> Rubber made Toys</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Support</h4>
                                <ul>
                                    <li><a href="#">Frequently Asked Questions</a></li>
                                    <li><a href="#">Terms & Conditions</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Report a Payment Issue</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer bottom -->
                <div class="row align-items-center">
                    <div class="col-xl-7 col-lg-8 col-md-7">
                        <div class="footer-copy-right">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>                  
                        </div>
                    </div>
                    <div class="col-xl-5 col-lg-4 col-md-5">
                        <div class="footer-copy-right f-right">
                            <!-- social -->
                            <div class="footer-social">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="https://www.facebook.com/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fab fa-behance"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!--? Search model Begin -->
    <div class="search-model-box">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-btn">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Searching key.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- JS here -->

    <script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static './assets/js/popper.min.js' %}"></script>
    {% comment %} <script src="{% static './assets/js/bootstrap.min.js' %}"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static './assets/js/slick.min.js' %}"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="{% static './assets/js/wow.min.js' %}"></script>
    <script src="{% static './assets/js/animated.headline.js' %}"></script>
    <script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static './assets/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static './assets/js/jquery.sticky.js' %}"></script>
    
    <!-- contact js -->
    <script src="{% static './assets/js/contact.js' %}"></script>
    <script src="{% static './assets/js/jquery.form.js' %}"></script>
    <script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
    <script src="{% static './assets/js/mail-script.js' %}"></script>
    <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static './assets/js/plugins.js' %}"></script>
    <script src="{% static './assets/js/main.js' %}"></script>
    
</body>
</html>

user/templates/user/login.html
{% extends 'user/index.html'%}
{% load static %}
{% block body%}
<section class="login_part section_padding " style = 'margin-top : -160px; margin-bottom : -160px'>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>New to our Shop?</h2>
                        <p>There are advances being made in science and technology
                            everyday, and a good example of this is the</p>
                        <a href="{% url 'register'%}" class="btn_3">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Welcome Back ! <br>
                            Please Sign in now</h3>
                        <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                            {%csrf_token%}
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="email" name="email" value=""
                                    placeholder="Email">
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <input type="password" class="form-control" id="password" name="password" value=""
                                    placeholder="Password">
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="creat_account d-flex align-items-center">
                                    <input type="checkbox" id="f-option" name="selector">
                                    <label for="f-option">Remember me</label>
                                </div>
                                <button type="submit" value="submit" class="btn_3">
                                    log in
                                </button>
                                <a class="lost_pass" href="#">forget password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body%}

user/templates/user/register.html
{% extends 'user/index.html'%}
{% load static %}
{% block body%}
<section class="login_part section_padding " style = 'margin-top : -160px; margin-bottom : -160px'>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>Already have an account?</h2>
                        <p>There are advances being made in science and technology
                            everyday, and a good example of this is the</p>
                        <a href="{%url 'user_login'%}" class="btn_3">Login</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Welcome  <br>
                            Please Sign up now</h3>
                            <form class="row contact_form" action="{% url 'register' %}" method="post" novalidate="novalidate">
                                {% csrf_token %}
                                
                                <div class="col-md-12 form-group p_star">
                                    <label for="id_name">Name</label>
                                    {{ form.name }}
                                </div>
                            
                                <div class="col-md-12 form-group p_star">
                                    <label for="id_email">Email</label>
                                    {{ form.email }}
                                </div>
                            
                                <div class="col-md-12 form-group p_star" style = 'margin-top:20px'>
                                    <label for="id_password1">Password &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</label>
                                    {{ form.password1 }}  <!-- Styled password1 -->
                                </div>
                            
                                <div class="col-md-12 form-group p_star" style = 'margin-top:20px; margin-bottom:30px'>
                                    <label for="id_password2">Confirm Password  &nbsp; &nbsp;&nbsp;</label>
                                    {{ form.password2 }}  <!-- Styled password2 -->
                                </div>
                                
                                <button type="submit" value="submit" class="btn_3">Sign up</button>
                            </form>
                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body%}

user/templates/user/test.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="stylesheet" href="{% static 'myfirst.css' %}">
<body>
<h1>title</h1>


</body>
</html>